import { ProductSpec } from './types'

export const productData: ProductSpec[] = [
  {
    id: 'header-Display',
    feature: '🖥️ Display',
    category: 'Display',
    isHeader: true,
    iphone15: '',
    galaxyS24: '',
    pixel8: '',
    iphone15Pro: '',
  },
  {
    feature: 'Display Size',
    category: 'Display',
    iphone15: '6.1"',
    galaxyS24: '6.2"',
    pixel8: '6.2"',
    iphone15Pro: '6.1"',
    id: 'spec-0',
  },
  {
    feature: 'Resolution',
    category: 'Display',
    iphone15: '2556×1179',
    galaxyS24: '2340×1080',
    pixel8: '2400×1080',
    iphone15Pro: '2556×1179',
    id: 'spec-1',
  },
  {
    feature: 'Refresh Rate',
    category: 'Display',
    iphone15: '60Hz',
    galaxyS24: '120Hz',
    pixel8: '120Hz',
    iphone15Pro: '120Hz',
    id: 'spec-2',
  },
  {
    id: 'header-Performance',
    feature: '⚡️ Performance',
    category: 'Performance',
    isHeader: true,
    iphone15: '',
    galaxyS24: '',
    pixel8: '',
    iphone15Pro: '',
  },
  {
    feature: 'Processor',
    category: 'Performance',
    iphone15: 'A16 Bionic',
    galaxyS24: 'Snapdragon 8 Gen 3',
    pixel8: 'Tensor G3',
    iphone15Pro: 'A17 Pro',
    id: 'spec-3',
  },
  {
    feature: 'RAM',
    category: 'Performance',
    iphone15: '6GB',
    galaxyS24: '8GB',
    pixel8: '8GB',
    iphone15Pro: '8GB',
    id: 'spec-4',
  },
  {
    id: 'header-Storage',
    feature: '💾 Storage',
    category: 'Storage',
    isHeader: true,
    iphone15: '',
    galaxyS24: '',
    pixel8: '',
    iphone15Pro: '',
  },
  {
    feature: 'Storage',
    category: 'Storage',
    iphone15: '128GB',
    galaxyS24: '128GB',
    pixel8: '128GB',
    iphone15Pro: '128GB',
    id: 'spec-5',
  },
  {
    feature: 'Expandable Storage',
    category: 'Storage',
    iphone15: 'No',
    galaxyS24: 'Yes',
    pixel8: 'No',
    iphone15Pro: 'No',
    id: 'spec-6',
  },
  {
    id: 'header-Camera',
    feature: '📸 Camera',
    category: 'Camera',
    isHeader: true,
    iphone15: '',
    galaxyS24: '',
    pixel8: '',
    iphone15Pro: '',
  },
  {
    feature: 'Main Camera',
    category: 'Camera',
    iphone15: '48MP',
    galaxyS24: '50MP',
    pixel8: '50MP',
    iphone15Pro: '48MP',
    id: 'spec-7',
  },
  {
    feature: 'Ultra Wide',
    category: 'Camera',
    iphone15: '12MP',
    galaxyS24: '12MP',
    pixel8: '12MP',
    iphone15Pro: '12MP',
    id: 'spec-8',
  },
  {
    feature: 'Telephoto',
    category: 'Camera',
    iphone15: 'No',
    galaxyS24: '10MP (3x)',
    pixel8: 'No',
    iphone15Pro: '12MP (3x)',
    id: 'spec-9',
  },
  {
    id: 'header-Battery',
    feature: '🔋 Battery',
    category: 'Battery',
    isHeader: true,
    iphone15: '',
    galaxyS24: '',
    pixel8: '',
    iphone15Pro: '',
  },
  {
    feature: 'Battery',
    category: 'Battery',
    iphone15: '3349mAh',
    galaxyS24: '4000mAh',
    pixel8: '4575mAh',
    iphone15Pro: '3274mAh',
    id: 'spec-10',
  },
  {
    feature: 'Wireless Charging',
    category: 'Battery',
    iphone15: 'Yes',
    galaxyS24: 'Yes',
    pixel8: 'Yes',
    iphone15Pro: 'Yes',
    id: 'spec-11',
  },
  {
    feature: 'Fast Charging',
    category: 'Battery',
    iphone15: '20W',
    galaxyS24: '25W',
    pixel8: '30W',
    iphone15Pro: '27W',
    id: 'spec-12',
  },
  {
    id: 'header-Build',
    feature: '🛠️ Build',
    category: 'Build',
    isHeader: true,
    iphone15: '',
    galaxyS24: '',
    pixel8: '',
    iphone15Pro: '',
  },
  {
    feature: 'Water Resistance',
    category: 'Build',
    iphone15: 'IP68',
    galaxyS24: 'IP68',
    pixel8: 'IP68',
    iphone15Pro: 'IP68',
    id: 'spec-13',
  },
  {
    feature: 'Material',
    category: 'Build',
    iphone15: 'Aluminum',
    galaxyS24: 'Aluminum',
    pixel8: 'Aluminum',
    iphone15Pro: 'Titanium',
    id: 'spec-14',
  },
  {
    feature: 'Weight',
    category: 'Build',
    iphone15: '171g',
    galaxyS24: '167g',
    pixel8: '187g',
    iphone15Pro: '187g',
    id: 'spec-15',
  },
  {
    id: 'header-Price',
    feature: '💰 Price',
    category: 'Price',
    isHeader: true,
    iphone15: '',
    galaxyS24: '',
    pixel8: '',
    iphone15Pro: '',
  },
  {
    feature: 'Starting Price',
    category: 'Price',
    iphone15: '$799',
    galaxyS24: '$799',
    pixel8: '$699',
    iphone15Pro: '$999',
    id: 'spec-16',
  },
]
